# Generated by ChatGPT and modified from there
import json
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Assume jsonData is a string containing the JSON data
with open("crokinele_results.json", "r") as f:
    jsonData = f.read()

data = json.loads(jsonData)

# Access the results HTML and hits data properties of the object
resultsHtml = data["results"]
hitsData = data["hits"]

# Assume tableHtml is a string containing the HTML code for the table
soup = BeautifulSoup(resultsHtml, "html.parser")
table = soup.find("thead")

# Convert the table data to a list of lists
table_data = []
for row in table.find_all("tr"):
    row_data = [cell.get_text(strip=True) for cell in row.find_all(["th", "td"])]
    table_data.append(row_data)
    
df = pd.DataFrame(table_data[1:], columns=table_data[0])
print(df)    

