# Generated by ChatGPT and modified from there
library(jsonlite)
library(rvest)

# Assume jsonData is a string containing the JSON data
data <- fromJSON("crokinele_results.json")

# Access the results HTML and hits data properties of the object
resultsHtml <- data$results
hitsData <- data$hits

# Assume tableHtml is a string containing the HTML code for the table
table <- read_html(resultsHtml) %>% 
  html_nodes("thead") %>% 
  html_table(fill = TRUE)
